### ISSUE TITLE
[BUG] UXCore causing error in Unity 6.3 because of legacyDialogue in package and new breaking serializefield rules

### ISSUE THREAD

**Issue by RCrolyFex** [MixedRealityToolkit/MixedRealityToolkit-Unity#1101]
## Describe the bug

UXcore 3.3.0 throws an error when imported into Unity 6.3:

`Packages\org.mixedrealitytoolkit.uxcore\LegacyDialog\DialogButton.cs(20,6): error CS0592: Attribute 'SerializeField' is not valid on this declaration type. It is only valid on 'field' declarations`

## To reproduce

Import the ux core 3.3.0 package into unity 6.3

## Expected behavior

No errors :)

- Unity Version 6000.3.9f1
- UXcore 3.3.0
- 
## Target platform (please complete the following information)

- OpenXR

## Additional context
https://discussions.unity.com/t/planned-breaking-changes-in-unity-6-3/1646418

**Comment by keveleigh** [comment]
Yeah, we've done work in the 4.0 packages to more properly adopt newer Unity versions, along with adopting the newer packages, like XRI 3.x, that become the recommended versions.

Generally, I try to keep the latest MRTK mainline (so, currently the 3.x packages) buildable on newer Unity versions, even if we don't take advantage of any new features.

As far as a full release of the 4.0 packages, we're working on figuring that out. We're close! But I can't commit to a specific date just yet.
