### PR TITLE
Fix object identity APIs for Unity 6.4 and newer

### LINKED ISSUE #1134: [BUG] Unity 6000.5 compilation fails because GetInstanceID is an obsolete error
## Describe the bug

The latest stable MRTK packages do not compile with Unity 6000.5 because Unity changed `UnityEngine.Object.GetInstanceID()` from an obsolete warning to an obsolete error.

Confirmed affected packages:

- `org.mixedrealitytoolkit.input` 3.3.0
- `org.mixedrealitytoolkit.spatialmanipulation` 3.4.0

The same calls are also present in Input 4.0.0-pre.2 and the current `main` branch.

This blocks Editor compilation before entering Play Mode or building the project.

## To reproduce

1. Open a project with Unity 6000.5.5f1.
2. Install MRTK Input 3.3.0 and Spatial Manipulation 3.4.0.
3. Allow Unity to compile the packages.
4. Observe the CS0619 errors.

## Actual behavior

Spatial Manipulation 3.4.0:

```text
Editor/Constraints/ConstraintManagerEditor.cs(291,66): error CS0619: 'Object.GetInstanceID()' is obsolete: 'GetInstanceID is deprecated. Use GetEntityId instead. This will be removed in a future version.'
Editor/Constraints/ConstraintManagerEditor.cs(373,76): error CS0619: 'Object.GetInstanceID()' is obsolete: 'GetInstanceID is deprecated. Use GetEntityId instead. This will be removed in a future version.'
```

Input 3.3.0:

```text
Editor/Inspectors/InteractionModeManagerEditor.cs(91,25): error CS0619: 'Object.GetInstanceID()' is obsolete: 'GetInstanceID is deprecated. Use GetEntityId instead. This will be removed in a future version.'
```

Affected patterns include:

```csharp
constraintManager.GetInstanceID()
selectedConstraintManager.GetInstanceID()

HashSet<int> seenInstanceIDs = new HashSet<int>();
int instanceID = key.objectReferenceValue.GetInstanceID();
```

## Expected behavior

MRTK should compile on Unity 6000.5 using `EntityId` while retaining compatibility with the packages' older supported Unity versions.

For example, the duplicate mapping logic can use `HashSet<EntityId>`, `GetEntityId()`, and `EntityId.None` on supported Unity versions. Conditional compilation or a compatibility helper may be needed because the packages currently support Unity versions where `EntityId` is unavailable.

## Screenshots

Unity Console reports the CS0619 errors above during package compilation.

## Your setup

- Unity Version: 6000.5.5f1
- MRTK Input: 3.3.0
- MRTK Spatial Manipulation: 3.4.0
- Editor OS: macOS
- Regression check: Unity 6000.4.6f1 reports `GetInstanceID()` as an obsolete warning; Unity 6000.5.5f1 reports it as an obsolete error.

## Target platform

Editor compilation issue; platform-independent. Observed in an iOS/OpenXR project.

## Additional context

- The latest stable Input 3.3.0 package contains the obsolete call.
- Input 4.0.0-pre.2 and the current `main` branch also contain the same call.
- Related Graphics Tools issue: https://github.com/microsoft/MixedReality-GraphicsTools-Unity/issues/245

### PR DESCRIPTION
**Pull request by gdgeek**
## Summary

Unity 6.6 reports CS0619 for `Object.GetInstanceID()`, preventing the Input and SpatialManipulation editor assemblies from compiling.

Use `GetEntityId()` on Unity 6.4 and newer while retaining `GetInstanceID()` on earlier editors. Controller mapping validation stores full `EntityId` values, including `EntityId.None` for empty or missing references, so duplicate detection retains its existing behavior without narrowing IDs to `int`. The constraint manager label and the "Go to component" highlight query both use the same ID API.

Fixes #1134.

## Validation

- Reproduced the three existing CS0619 errors using Unity 6000.6.0f1's bundled compiler and the affected editor assembly response files.
- Compiled both complete affected editor assemblies with the patched files against Unity 6000.6.0f1 editor assemblies: passed.
- Compiled both affected editor assemblies against Unity 6000.4.12f1 editor assemblies using its bundled compiler: passed.
- Forced the legacy preprocessor branches and compiled both affected assemblies against Unity 6000.4.12f1: passed.
- `git diff --check`: passed.

The direct compiler checks use existing MRTK dependency assemblies. They do not replace interactive Inspector checks, a full project migration, or device testing. Unity versions earlier than 6.4 were not installed for execution; their original code paths are preserved.

### CODE REVIEW

**Comment by keveleigh** [comment]
Looks good to me! Will pull it down and test it out.

One note: please add changelog entries for these!

```
WARNING: Package 'org.mixedrealitytoolkit.input' has changes, but its CHANGELOG.md was not updated. This is not always an issue but usually is
WARNING: Package 'org.mixedrealitytoolkit.spatialmanipulation' has changes, but its CHANGELOG.md was not updated. This is not always an issue but usually is
```

**Comment by keveleigh** [comment]
@gdgeek I went ahead and:

1. Added changelog entries
2. Updated some related calls in `FindObjectUtility` which were also newly deprecated in 6.4 due to the entity ID change

Hope that's okay! Running a few more local tests, then I'll merge

**Review by keveleigh — APPROVED** [review]
